version: '2'
services:
    suntrackit-app:
        image: suntrackit
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://suntrackit-mysql:3306/suntrackit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://suntrackit-elasticsearch:9200
        ports:
            - 8080:8080
    suntrackit-mysql:
        extends:
            file: mysql.yml
            service: suntrackit-mysql
    suntrackit-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: suntrackit-elasticsearch
